Repository akai-org/woof-enactus, pull requests merged in 2025-03, with the labels that each got.

#9 Add backend app
  README.md
  apps/server/.env.example
  apps/server/.gitignore
  apps/server/README.md
  apps/server/eslint.config.mjs
  apps/server/nest-cli.json
  apps/server/package.json
  apps/server/prisma/migrations/20250301200211_init/migration.sql
  apps/server/prisma/migrations/migration_lock.toml
  apps/server/prisma/schema.prisma
  apps/server/src/app.controller.spec.ts
  apps/server/src/app.controller.ts
  apps/server/src/app.module.ts
  apps/server/src/app.service.ts
  apps/server/src/main.ts
  apps/server/src/prisma/prisma.module.ts
  apps/server/src/prisma/prisma.service.ts
  apps/server/test/app.e2e-spec.ts
  apps/server/tsconfig.build.json
  apps/server/tsconfig.json
  compose.dev.yml
  jest.config.ts
  package-lock.json
  package.json
Labels: backend

#16 feat(markers): markers/marker endpoints, seed
  .gitignore
  apps/server/package.json
  apps/server/prisma/seed.ts
  apps/server/src/app.module.ts
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.module.ts
  apps/server/src/partners/partners.service.ts
  package-lock.json
Labels: enhancement, backend

#17 feat: Add Swagger UI
  apps/server/README.md
  apps/server/package.json
  apps/server/src/main.ts
  package-lock.json
Labels: enhancement, backend

#19 fix: Add error handling for partners endpoints
  apps/server/eslint.config.mjs
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
Labels: backend

#22 docs: Change prisma script
  apps/server/README.md
  apps/server/package.json
Labels: documentation, backend

#20 Types and data validation
  apps/client/package.json
  apps/server/.gitignore
  apps/server/package.json
  apps/server/setup_codegen.sh
  apps/server/src/main.ts
  apps/server/src/partners/dto/CreatePartnerDto.ts
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
  apps/server/src/types/index.ts
  package-lock.json
  package.json
  packages/woof-api-client/.gitignore
  packages/woof-api-client/.npmignore
  packages/woof-api-client/.swagger-codegen-ignore
  packages/woof-api-client/.swagger-codegen/VERSION
  packages/woof-api-client/README.md
  packages/woof-api-client/api.ts
  packages/woof-api-client/apis/app-api.ts
  packages/woof-api-client/apis/partners-api.ts
  packages/woof-api-client/base.ts
  packages/woof-api-client/configuration.ts
  packages/woof-api-client/git_push.sh
  packages/woof-api-client/index.ts
  packages/woof-api-client/models/create-partner-dto.ts
  packages/woof-api-client/models/get-all-partners-response.ts
  packages/woof-api-client/models/index.ts
  packages/woof-api-client/package.json
  packages/woof-api-client/tsconfig.json
Labels: enhancement, backend

#18 feature: navbar,footer,theme
  apps/client/package.json
  apps/client/src/app/layout.tsx
  apps/client/src/components/Footer.tsx
  apps/client/src/components/Navbar.tsx
  apps/client/src/constants/theme.ts
  apps/client/src/provider.tsx
  apps/client/src/providers.tsx
  package-lock.json
Labels: frontend

#25 feat: Add NestConfig module
  apps/server/.env.example
  apps/server/env.d.ts
  apps/server/package.json
  apps/server/src/app.module.ts
  apps/server/src/main.ts
  package-lock.json
Labels: enhancement, backend

#24 Places filters #15
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
Labels: enhancement, backend

#37 feat: endpoint for partner profile
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
Labels: enhancement, backend

#36 feat(api): partner search by address and address
  apps/server/README.md
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
  apps/server/src/prisma/prisma.service.ts
  package-lock.json
  package.json
Labels: enhancement, backend

#38 Feat: crud operations
  apps/server/prisma/migrations/20250316200252_cascade_delete/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  apps/server/src/partners/dto/CreatePartnerDto.ts
  apps/server/src/partners/dto/UpdatePartnerDto.ts
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
Labels: enhancement, backend

#40 feat: add map markers with popup
  .github/CODEOWNERS
  apps/client/.env.example
  apps/client/.gitignore
  apps/client/package.json
  apps/client/public/marker-icon.svg
  apps/client/src/app/fonts.ts
  apps/client/src/app/layout.tsx
  apps/client/src/app/page.tsx
  apps/client/src/components/Btn.tsx
  apps/client/src/components/Footer.tsx
  apps/client/src/components/Navbar.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/map/Location.tsx
  apps/client/src/components/map/Map.tsx
  apps/client/src/components/map/MapMarker.tsx
  apps/client/src/components/map/types.ts
  apps/client/src/constants/colors-palette-design.md
  apps/client/src/constants/index.ts
  apps/client/src/constants/partnersApi.ts
  apps/client/src/constants/theme.ts
  apps/client/src/providers.tsx
  apps/client/src/style.css
  apps/server/prisma/migrations/20250314142337_add_coordinates_to_partner/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  apps/server/src/partners/partners.service.ts
  package-lock.json
  package.json
Labels: enhancement, frontend

#32 feat: responsive header&footer
  apps/client/src/app/layout.tsx
  apps/client/src/components/Footer.tsx
  apps/client/src/components/Navbar.tsx
  apps/client/src/components/index.ts
Labels: frontend

#30 Map search bar
  README.md
  apps/client/src/app/page.tsx
  apps/client/src/components/Footer.tsx
  apps/client/src/components/Navbar.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/map/Map.tsx
  apps/client/src/components/mapSearchBar/Filters.tsx
  apps/client/src/components/mapSearchBar/Legend.tsx
  apps/client/src/components/mapSearchBar/SearchBar.tsx
  apps/server/package.json
  compose.dev.yml
  package-lock.json
  package.json
Labels: enhancement, frontend

#39 35 feat partner panel
  apps/client/next.config.ts
  apps/client/src/app/layout.tsx
  apps/client/src/app/not-found.tsx
  apps/client/src/app/page.tsx
  apps/client/src/app/placowki/[uuid]/page.tsx
  apps/client/src/components/Footer.tsx
  apps/client/src/components/Navbar.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/map-search-bar/Filters.tsx
  apps/client/src/components/map-search-bar/Legend.tsx
  apps/client/src/components/map-search-bar/SearchBar.tsx
  apps/client/src/components/map-search-bar/index.ts
  apps/client/src/components/map/Map.tsx
  apps/client/src/components/map/MapMarker.tsx
  apps/client/src/components/map/index.ts
  apps/client/src/components/partner/PartnerEvents.tsx
  apps/client/src/components/partner/PartnerInfo.tsx
  apps/client/src/components/partner/PartnerNeeds.tsx
  apps/client/src/components/partner/index.ts
  apps/client/src/components/ui/Btn.tsx
  apps/client/src/components/ui/Link.tsx
  apps/client/src/types.ts
Labels: enhancement, frontend

#49 feat: about us page
  README.md
  apps/client/public/about-us-1.png
  apps/client/public/about-us-2.png
  apps/client/public/about-us-3.png
  apps/client/public/about-us-4.png
  apps/client/public/about-us-bg.png
  apps/client/src/app/o-nas/page.tsx
  apps/client/src/components/map-search-bar/SearchBar.tsx
Labels: enhancement, frontend
