Repository akai-org/woof-enactus, pull requests merged in 2025-04, with the labels that each got.

#47 Needed Goods DB Schema
  apps/server/package.json
  apps/server/prisma/migrations/20250325113223_add_needed_goods_table/migration.sql
  apps/server/prisma/migrations/20250401171902_add_name_to_neededgood/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  package-lock.json
Labels: enhancement, backend

#51 More precise partner search #46
  apps/server/prisma/migrations/20250331090009_add_trgm_index/migration.sql
  apps/server/prisma/migrations/20250331090043_add_trgm_index/migration.sql
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
Labels: backend, fix

#54 feat: addition to partner profile: email and image
  apps/client/src/components/partner/PartnerInfo.tsx
  apps/client/src/types.ts
  apps/server/prisma/migrations/20250402053847_goods_table_update/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  package-lock.json
Labels: enhancement, backend

#55 refactor: changed uuid to slug
  README.md
  apps/client/src/app/placowki/[slug]/page.tsx
  apps/client/src/components/map/MapMarker.tsx
  apps/client/src/types.ts
  apps/server/package.json
  apps/server/prisma/migrations/20250403104750_add_slug/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  apps/server/src/partners/dto/CreatePartnerDto.ts
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
  package-lock.json
  package.json
Labels: enhancement

#50 fear: 41-show-nearby
  apps/client/public/user-marker-icon.svg
  apps/client/src/app/layout.tsx
  apps/client/src/app/page.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/map-search-bar/SearchBar.tsx
  apps/client/src/components/map/Location.tsx
  apps/client/src/components/map/Map.tsx
  apps/client/src/components/map/MapMarker.tsx
  apps/client/src/components/ui/Button.tsx
  apps/client/src/components/ui/Toast.tsx
  apps/client/src/components/ui/Tooltip.tsx
  apps/client/src/components/ui/index.ts
  apps/client/src/constants/index.ts
  apps/client/src/constants/toaster.ts
  package-lock.json
Labels: enhancement, frontend

#58 feat: api integration with search input & filters
  apps/client/eslint.config.mjs
  apps/client/public/marker-200-green.svg
  apps/client/public/marker-400-yellow.svg
  apps/client/public/marker-500-green.svg
  apps/client/public/marker-700-green.svg
  apps/client/src/api/getPartnerProfile.ts
  apps/client/src/api/getPartners.ts
  apps/client/src/api/index.ts
  apps/client/src/app/page.tsx
  apps/client/src/app/placowki/[slug]/page.tsx
  apps/client/src/components/Navbar.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/map-search-bar/Filters.tsx
  apps/client/src/components/map-search-bar/Legend.tsx
  apps/client/src/components/map-search-bar/Search.tsx
  apps/client/src/components/map-search-bar/SearchBar.tsx
  apps/client/src/components/map/Location.tsx
  apps/client/src/components/map/Map.tsx
  apps/client/src/components/map/MapMarker.tsx
  apps/client/src/components/partner/PartnerInfo.tsx
  apps/client/src/components/ui/Button.tsx
  apps/client/src/components/ui/Checkbox.tsx
  apps/client/src/components/ui/GoBackButton.tsx
  apps/client/src/components/ui/Link.tsx
  apps/client/src/components/ui/index.ts
  apps/client/src/constants/index.ts
  apps/client/src/constants/legend.ts
  apps/client/src/constants/partnersApi.ts
  apps/client/src/types.ts
  apps/client/tsconfig.json
  package-lock.json
Labels: enhancement, frontend

#62 feat multiple PartnerTypes
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
Labels: backend

#66 added timestamp to NeededGoods, updated seed.ts
  apps/server/prisma/migrations/20250410091719_add_timestamps_to_neededgoods/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
Labels: enhancement, backend

#74 fix note in goods database
  apps/client/src/api/getPartnerNeeds.ts
  apps/client/src/api/index.ts
  apps/client/src/components/partner/PartnerNeeds.tsx
  apps/client/src/types.ts
  apps/server/prisma/migrations/20250415181103_note_fix/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  apps/server/src/partners/partners.service.ts
Labels: backend, fix

#61 feat: Authorization
  apps/server/.env.example
  apps/server/env.d.ts
  apps/server/eslint.config.mjs
  apps/server/package.json
  apps/server/prisma/migrations/20250408102530_add_partner_account/migration.sql
  apps/server/prisma/migrations/20250408103046_add_unique_constraint_to_username/migration.sql
  apps/server/prisma/migrations/20250409091149_fix_partner_partner_account_relation/migration.sql
  apps/server/prisma/migrations/20250416105501_add_unique_to_needed_goods_partner/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  apps/server/src/accounts/accounts.controller.ts
  apps/server/src/accounts/accounts.module.ts
  apps/server/src/accounts/accounts.service.ts
  apps/server/src/app.module.ts
  apps/server/src/auth/auth.controller.ts
  apps/server/src/auth/auth.guard.ts
  apps/server/src/auth/auth.module.ts
  apps/server/src/auth/auth.service.ts
  apps/server/src/auth/dto/SignInDto.ts
  apps/server/src/auth/refresh.guard.ts
  apps/server/src/main.ts
  apps/server/src/partners/dto/CreatePartnerDto.ts
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.service.ts
  apps/server/src/types/index.ts
  apps/server/src/utils/user.decorator.ts
  package-lock.json
Labels: enhancement, backend

#77 feat db model and CRUD for partner events #70
  apps/server/prisma/migrations/20250427164149_partner_event/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  apps/server/src/partners/dto/CreatePartnerEventDto.ts
  apps/server/src/partners/dto/UpdatePartnerEventDto.ts
  apps/server/src/partners/partner-event.controller.ts
  apps/server/src/partners/partner-event.service.ts
  apps/server/src/partners/partners.module.ts
  packages/@types/woof/index.d.ts
Labels: enhancement, backend
