Repository akai-org/woof-enactus, pull requests merged in 2025-05, with the labels that each got.

#72 Shell script to automate launch of the app
  .gitignore
  apps/server/package.json
  apps/server/prisma/seed.ts
  apps/server/tsconfig.json
  compose.dev.yml
  dev.Dockerfile
  package.json
Labels: enhancement, devops

#80 Refactor events and goods #79
  apps/client/src/api/getPartnerNeeds.ts
  apps/server/package.json
  apps/server/prisma/migrations/20250503111804_partner_event_refactor/migration.sql
  apps/server/prisma/migrations/migration_lock.toml
  apps/server/prisma/schema.prisma
  apps/server/prisma/seed.ts
  apps/server/setup_codegen.sh
  apps/server/src/app.module.ts
  apps/server/src/events/dto/CreateEventDto.ts
  apps/server/src/events/dto/UpdateEventDto.ts
  apps/server/src/events/events.controller.ts
  apps/server/src/events/events.module.ts
  apps/server/src/events/events.service.ts
  apps/server/src/goods/dto/CreateNeededGoodsDto.ts
  apps/server/src/goods/dto/UpdateNeededGoodsDto.ts
  apps/server/src/goods/goods.controller.ts
  apps/server/src/goods/goods.service.ts
  apps/server/src/goods/googs.module.ts
  apps/server/src/partners/dto/UpdatePartnerEventDto.ts
  apps/server/src/partners/partner-event.service.ts
  apps/server/src/partners/partners.controller.ts
  apps/server/src/partners/partners.module.ts
  apps/server/src/partners/partners.service.ts
  dev.Dockerfile
  package.json
Labels: backend, fix

#83 Add CI/CD Pipeline
  .dockerignore
  .github/workflows/release.yaml
  apps/client/next.config.ts
  apps/client/package.json
  apps/client/src/app/placowki/[slug]/page.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/map/index.ts
  apps/server/package.json
  apps/server/pnpm-workspace.yaml
  compose.dev.yml
  compose.prod.yml
  dev.Dockerfile
  package-lock.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  prod.Dockerfile
Labels: devops

#81 #71 support table
  apps/client/src/app/page.tsx
  apps/client/src/app/wsparcie/page.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/joinus/container.tsx
  apps/client/src/components/joinus/index.ts
  apps/client/src/components/map/MapMarker.tsx
  apps/client/src/components/partners-table/Table.tsx
  apps/client/src/components/partners-table/index.ts
  apps/client/src/constants/getPartnerTypeName.ts
  apps/client/src/constants/index.ts
  apps/client/src/style.css
Labels: frontend

#105 fix: error during frontend build (type error)
  apps/client/src/components/map/Map.tsx
Labels: release

#100 Login panel
  apps/client/package.json
  apps/client/src/actions/index.ts
  apps/client/src/actions/loginAction.ts
  apps/client/src/actions/refreshAction.ts
  apps/client/src/actions/registerAction.ts
  apps/client/src/app/(auth)/logowanie/page.tsx
  apps/client/src/app/(auth)/rejestracja/_.tsx
  apps/client/src/app/api/auth/route.ts
  apps/client/src/app/page.tsx
  apps/client/src/app/panel-placowki/page.tsx
  apps/client/src/app/placowki/[slug]/page.tsx
  apps/client/src/app/wsparcie/page.tsx
  apps/client/src/components/joinus/container.tsx
  apps/client/src/components/layout/NavLink.tsx
  apps/client/src/components/layout/Navbar.tsx
  apps/client/src/hooks/index.ts
  apps/client/src/hooks/useAuth.ts
  apps/client/src/middleware.ts
  apps/client/src/types.ts
  apps/server/package.json
  pnpm-lock.yaml
Labels: enhancement, frontend

#108 99 better error loading states handling
  apps/client/.env.example
  apps/client/package.json
  apps/client/src/app/global-error.tsx
  apps/client/src/app/o-nas/page.tsx
  apps/client/src/app/page.tsx
  apps/client/src/app/wsparcie/page.tsx
  apps/client/src/assets/about-us-1.png
  apps/client/src/assets/about-us-2.png
  apps/client/src/assets/about-us-3.png
  apps/client/src/assets/about-us-4.png
  apps/client/src/components/index.ts
  apps/client/src/components/join-us/container.tsx
  apps/client/src/components/layout/Footer.tsx
  apps/client/src/components/layout/Navbar.tsx
  apps/client/src/components/ui/GoBackButton.tsx
  apps/client/src/components/ui/index.ts
  apps/client/src/features/map/Map.tsx
  apps/client/src/features/map/MapNoSsr.tsx
  apps/client/src/features/map/SkeletonMap.tsx
  apps/client/src/features/map/index.ts
  apps/client/src/features/map/map.config.ts
  apps/client/src/features/map/search-bar/Search.tsx
  apps/client/src/features/map/search-bar/SearchBar.tsx
  apps/client/src/hooks/useAuth.ts
  apps/client/src/providers.tsx
  pnpm-lock.yaml
Labels: frontend

#109 fix: added protection tag source branch
  .github/workflows/release.yaml
Labels: devops

#112 fix: `save-state` is no longer used
  .github/workflows/release.yaml
Labels: fix, devops

#118 Release v1.0.4
  .github/workflows/release.yaml
Labels: release
